/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basdatgui;

import java.awt.*;
import java.math.*;
import java.sql.*;
import java.text.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author WINDOWS 11
 */
public class AdminUjiKlinis extends javax.swing.JFrame {

    /**
     * Creates new form AdminUjiKlinis
     */
    public AdminUjiKlinis() {
        initComponents();
        tableUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backMenuButton = new javax.swing.JButton();
        panelTitle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FrameLabel = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableUjiKlinis = new javax.swing.JTable();
        panelBatch = new javax.swing.JPanel();
        txtBatch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panelProtein = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtProtein = new javax.swing.JTextField();
        panelKadarAir = new javax.swing.JPanel();
        txtKadarAir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panelLemak = new javax.swing.JPanel();
        txtLemak = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        panelBesi = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtBesi = new javax.swing.JTextField();
        panelKalsium = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtKalsium = new javax.swing.JTextField();
        panelArsen = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtArsen = new javax.swing.JTextField();
        panelKadmium = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtKadmium = new javax.swing.JTextField();
        panelTimbal = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtTimbal = new javax.swing.JTextField();
        panelMerkuri = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtMerkuri = new javax.swing.JTextField();
        panelEcoli = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtEcoli = new javax.swing.JTextField();
        panelSalmonela = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtSalmonela = new javax.swing.JTextField();
        bSimpanButton = new javax.swing.JButton();
        bBatalButton = new javax.swing.JButton();
        bEditButton = new javax.swing.JButton();
        bHapusButton = new javax.swing.JButton();
        bTambahButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        backMenuButton.setText("back");
        backMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuButtonActionPerformed(evt);
            }
        });

        panelTitle.setPreferredSize(new java.awt.Dimension(404, 28));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ADMIN");

        FrameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FrameLabel.setText("HASIL UJI KLINIS");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FrameLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FrameLabel)
                .addContainerGap())
        );

        searchButton.setText("search");
        searchButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        txtSearch.setText("Batch number");
        txtSearch.setToolTipText("");

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addContainerGap())
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tableUjiKlinis.setAutoCreateRowSorter(true);
        tableUjiKlinis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "batch number", "protein (%)", "kadar air (%)", "lemak (%)", "besi/kg", "kalsium/kg", "arsen/kg", "kadmium/kg", "timbal/kg", "merkuri/kg", "E.coli/gram", "Salmonella/25 gram"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUjiKlinis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUjiKlinisMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableUjiKlinis);

        txtBatch.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel5.setText("Batch number");

        javax.swing.GroupLayout panelBatchLayout = new javax.swing.GroupLayout(panelBatch);
        panelBatch.setLayout(panelBatchLayout);
        panelBatchLayout.setHorizontalGroup(
            panelBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBatchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBatchLayout.setVerticalGroup(
            panelBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBatchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel6.setText("Protein (%)");

        txtProtein.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelProteinLayout = new javax.swing.GroupLayout(panelProtein);
        panelProtein.setLayout(panelProteinLayout);
        panelProteinLayout.setHorizontalGroup(
            panelProteinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProteinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(txtProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelProteinLayout.setVerticalGroup(
            panelProteinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProteinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProteinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtKadarAir.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel7.setText("Kadar air (%)");

        javax.swing.GroupLayout panelKadarAirLayout = new javax.swing.GroupLayout(panelKadarAir);
        panelKadarAir.setLayout(panelKadarAirLayout);
        panelKadarAirLayout.setHorizontalGroup(
            panelKadarAirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKadarAirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtKadarAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelKadarAirLayout.setVerticalGroup(
            panelKadarAirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKadarAirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKadarAirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKadarAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtLemak.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel9.setText("Lemak (%)");

        javax.swing.GroupLayout panelLemakLayout = new javax.swing.GroupLayout(panelLemak);
        panelLemak.setLayout(panelLemakLayout);
        panelLemakLayout.setHorizontalGroup(
            panelLemakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLemakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtLemak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelLemakLayout.setVerticalGroup(
            panelLemakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLemakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLemakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtLemak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel12.setText("Besi/kg");

        txtBesi.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelBesiLayout = new javax.swing.GroupLayout(panelBesi);
        panelBesi.setLayout(panelBesiLayout);
        panelBesiLayout.setHorizontalGroup(
            panelBesiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBesiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(txtBesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBesiLayout.setVerticalGroup(
            panelBesiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBesiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBesiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtBesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel14.setText("Kalsium/kg");

        txtKalsium.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelKalsiumLayout = new javax.swing.GroupLayout(panelKalsium);
        panelKalsium.setLayout(panelKalsiumLayout);
        panelKalsiumLayout.setHorizontalGroup(
            panelKalsiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKalsiumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtKalsium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelKalsiumLayout.setVerticalGroup(
            panelKalsiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKalsiumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKalsiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtKalsium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel16.setText("Arsen/kg");

        txtArsen.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelArsenLayout = new javax.swing.GroupLayout(panelArsen);
        panelArsen.setLayout(panelArsenLayout);
        panelArsenLayout.setHorizontalGroup(
            panelArsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArsenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtArsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelArsenLayout.setVerticalGroup(
            panelArsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArsenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtArsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel10.setText("Kadmium/kg");

        txtKadmium.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelKadmiumLayout = new javax.swing.GroupLayout(panelKadmium);
        panelKadmium.setLayout(panelKadmiumLayout);
        panelKadmiumLayout.setHorizontalGroup(
            panelKadmiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKadmiumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtKadmium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelKadmiumLayout.setVerticalGroup(
            panelKadmiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKadmiumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKadmiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtKadmium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel19.setText("Timbal/kg");

        txtTimbal.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelTimbalLayout = new javax.swing.GroupLayout(panelTimbal);
        panelTimbal.setLayout(panelTimbalLayout);
        panelTimbalLayout.setHorizontalGroup(
            panelTimbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTimbalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimbal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTimbalLayout.setVerticalGroup(
            panelTimbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTimbalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTimbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtTimbal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel15.setText("Merkuri/kg");

        txtMerkuri.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelMerkuriLayout = new javax.swing.GroupLayout(panelMerkuri);
        panelMerkuri.setLayout(panelMerkuriLayout);
        panelMerkuriLayout.setHorizontalGroup(
            panelMerkuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMerkuriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(txtMerkuri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMerkuriLayout.setVerticalGroup(
            panelMerkuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMerkuriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMerkuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtMerkuri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel17.setText("E.coli/g");

        txtEcoli.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelEcoliLayout = new javax.swing.GroupLayout(panelEcoli);
        panelEcoli.setLayout(panelEcoliLayout);
        panelEcoliLayout.setHorizontalGroup(
            panelEcoliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEcoliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtEcoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelEcoliLayout.setVerticalGroup(
            panelEcoliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEcoliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEcoliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtEcoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel18.setText("Salmonela spp./25gram");

        txtSalmonela.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelSalmonelaLayout = new javax.swing.GroupLayout(panelSalmonela);
        panelSalmonela.setLayout(panelSalmonelaLayout);
        panelSalmonelaLayout.setHorizontalGroup(
            panelSalmonelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalmonelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSalmonela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSalmonelaLayout.setVerticalGroup(
            panelSalmonelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalmonelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSalmonelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtSalmonela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bSimpanButton.setText("Simpan");
        bSimpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanButtonActionPerformed(evt);
            }
        });

        bBatalButton.setText("Batal");
        bBatalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalButtonActionPerformed(evt);
            }
        });

        bEditButton.setText("Edit");
        bEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditButtonActionPerformed(evt);
            }
        });

        bHapusButton.setText("Hapus");
        bHapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusButtonActionPerformed(evt);
            }
        });

        bTambahButton.setText("Tambah");
        bTambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backMenuButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(panelBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelBesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelKadmium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelEcoli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelKadarAir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelKalsium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelSalmonela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTimbal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelArsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelLemak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelMerkuri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSimpanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bBatalButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEditButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bHapusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bTambahButton)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backMenuButton)
                .addGap(3, 3, 3)
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelKadarAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelLemak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBesi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelKalsium, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelArsen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelKadmium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelTimbal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelMerkuri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEcoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSalmonela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambahButton)
                    .addComponent(bHapusButton)
                    .addComponent(bEditButton)
                    .addComponent(bBatalButton)
                    .addComponent(bSimpanButton))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuButtonActionPerformed
        new AdminMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMenuButtonActionPerformed

    private void bTambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahButtonActionPerformed
        try {
            PreparedStatement insert = sqlQuery("insert into "
                    + "uji_klinis(batch_number, persentase_protein, persentase_kadar_air, persentase_lemak, "
                    + "kandungan_besi_per_kg, kandungan_kalsium_per_kg, kandungan_arsen_per_kg, "
                    + "kandungan_kadmium_per_kg, kandungan_timbal_per_kg, kandungan_merkuri_per_kg, " 
                    + "kandungan_ecoli_per_g, kandungan_salmolella_ssp_per_25g)"
                    + "values(?,?,?,?,?,?,?,?,?,?,?,?)");
            insert.setString(1, txtBatch.getText() );
            insert.setBigDecimal(2, new BigDecimal(txtProtein.getText()));
            insert.setBigDecimal(3, new BigDecimal(txtKadarAir.getText()));
            insert.setBigDecimal(4, new BigDecimal(txtLemak.getText()));
            insert.setBigDecimal(5, new BigDecimal(txtBesi.getText()));
            insert.setBigDecimal(6, new BigDecimal(txtKalsium.getText()));
            insert.setBigDecimal(7, new BigDecimal(txtArsen.getText()));
            insert.setBigDecimal(8, new BigDecimal(txtKadmium.getText()));
            insert.setBigDecimal(9, new BigDecimal(txtTimbal.getText()));
            insert.setBigDecimal(10, new BigDecimal(txtMerkuri.getText()));
            insert.setBigDecimal(11, new BigDecimal(txtEcoli.getText()));
            insert.setBigDecimal(12, new BigDecimal(txtSalmonela.getText()));
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Data berhasil ditambahkan!");
            
            tableUpdate();            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error: " + e);
        }
    }//GEN-LAST:event_bTambahButtonActionPerformed

    private void bHapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableUjiKlinis.getModel();
        int selectedIndex = tableUjiKlinis.getSelectedRow();
        try {   
            int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to delete the record","Warning",JOptionPane.YES_NO_OPTION);
            
            if(dialogResult == JOptionPane.YES_OPTION){
                PreparedStatement delete = sqlQuery("delete from uji_klinis where batch_number = ?");

                delete.setString(1,model.getValueAt(selectedIndex, 0).toString());
                delete.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Delete");
                
                tableUpdate();
           }
        } catch (Exception e) {   
            JOptionPane.showMessageDialog(this,"Exception: " + e);
        }
    }//GEN-LAST:event_bHapusButtonActionPerformed

    private void bEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditButtonActionPerformed
        textEnabled(true);
        txtBatch.setEnabled(false);
        buttonScenario("edit");
    }//GEN-LAST:event_bEditButtonActionPerformed

    private void bBatalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalButtonActionPerformed
        tableClicked();
    }//GEN-LAST:event_bBatalButtonActionPerformed

    private void bSimpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanButtonActionPerformed
        try {   
            DefaultTableModel model = (DefaultTableModel) tableUjiKlinis.getModel();
            int selectedIndex = tableUjiKlinis.getSelectedRow();
            
            PreparedStatement update = sqlQuery("update uji_klinis "
                    + "set persentase_protein=?, persentase_kadar_air=?, persentase_lemak=?, "
                    + "kandungan_besi_per_kg=?, kandungan_kalsium_per_kg=?, kandungan_arsen_per_kg=?, "
                    + "kandungan_kadmium_per_kg=?, kandungan_timbal_per_kg=?, kandungan_merkuri_per_kg=?, " 
                    + "kandungan_ecoli_per_g=?, kandungan_salmolella_ssp_per_25g=?"
                    + "where batch_number=?");
            
            update.setBigDecimal(1, new BigDecimal(txtProtein.getText()));
            update.setBigDecimal(2, new BigDecimal(txtKadarAir.getText()));
            update.setBigDecimal(3, new BigDecimal(txtLemak.getText()));
            update.setBigDecimal(4, new BigDecimal(txtBesi.getText()));
            update.setBigDecimal(5, new BigDecimal(txtKalsium.getText()));
            update.setBigDecimal(6, new BigDecimal(txtArsen.getText()));
            update.setBigDecimal(7, new BigDecimal(txtKadmium.getText()));
            update.setBigDecimal(8, new BigDecimal(txtTimbal.getText()));
            update.setBigDecimal(9, new BigDecimal(txtMerkuri.getText()));
            update.setBigDecimal(10, new BigDecimal(txtEcoli.getText()));
            update.setBigDecimal(11, new BigDecimal(txtSalmonela.getText()));
            update.setString(12, txtBatch.getText() );
            
            update.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Record Updated");
            
            tableUpdate();
            tableClicked();
            
        } catch (HeadlessException | NumberFormatException | SQLException e) {
           JOptionPane.showMessageDialog(this,"Error: " + e);
        }
    }//GEN-LAST:event_bSimpanButtonActionPerformed

    private void tableUjiKlinisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUjiKlinisMouseClicked
        tableClicked();
    }//GEN-LAST:event_tableUjiKlinisMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        tableUpdate();
    }//GEN-LAST:event_formMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {
            PreparedStatement search = sqlQuery("SELECT * FROM uji_klinis " +
                    "WHERE batch_number LIKE ?");
            search.setString(1, "%" + txtSearch.getText() + "%");
            
            String tempSearch = txtSearch.getText();
            loadData(search);
            txtSearch.setText(tempSearch);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Exception: " + e);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUjiKlinis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUjiKlinis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUjiKlinis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUjiKlinis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUjiKlinis().setVisible(true);
            }
        });
    }
    
    
    /*
        REQUIRED METHODS
    */
    
    private PreparedStatement sqlQuery (String query){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection url = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=KeinasthaFarma;encrypt=true;trustServerCertificate=true","sa","1211125");
            PreparedStatement getQuery = url.prepareStatement(query);
            return getQuery;
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,"Error: " + e);
        }
        return null;
    }
    
    private void tableUpdate() {
        PreparedStatement display = sqlQuery("SELECT * FROM uji_klinis");
        loadData(display);
    }
    
    private void tableClicked(){
        int index = tableUjiKlinis.getSelectedRow();
        TableModel model = tableUjiKlinis.getModel();
                  
        txtBatch.setText(model.getValueAt(index, 0).toString());
        txtProtein.setText(model.getValueAt(index, 1).toString());
        txtKadarAir.setText(model.getValueAt(index, 2).toString());
        txtLemak.setText(model.getValueAt(index, 3).toString());
        txtBesi.setText(model.getValueAt(index, 4).toString());
        txtKalsium.setText(model.getValueAt(index, 5).toString());
        txtArsen.setText(model.getValueAt(index, 6).toString());
        txtKadmium.setText(model.getValueAt(index, 7).toString());
        txtTimbal.setText(model.getValueAt(index, 8).toString());
        txtMerkuri.setText(model.getValueAt(index, 9).toString());
        txtEcoli.setText(model.getValueAt(index, 10).toString());
        txtSalmonela.setText(model.getValueAt(index, 11).toString());
        textEnabled(false);
        buttonScenario("tabel");
    }
    
    private void loadData(PreparedStatement executeThis){
        try{
            int CC;
        
            ResultSet Rs = executeThis.executeQuery();
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();

            DefaultTableModel DFT = (DefaultTableModel) tableUjiKlinis.getModel();
            DFT.setRowCount(0);
            while (Rs.next()) {
                Vector v2 = new Vector();

                for (int ii = 1; ii <= CC; ii++) {
                        v2.add(Rs.getString("batch_number"));
                        v2.add(Rs.getString("persentase_protein"));
                        v2.add(Rs.getString("persentase_kadar_air"));
                        v2.add(Rs.getString("persentase_lemak"));
                        v2.add(Rs.getString("kandungan_besi_per_kg"));
                        v2.add(Rs.getString("kandungan_kalsium_per_kg"));
                        v2.add(Rs.getString("kandungan_arsen_per_kg"));
                        v2.add(Rs.getString("kandungan_kadmium_per_kg"));
                        v2.add(Rs.getString("kandungan_timbal_per_kg"));
                        v2.add(Rs.getString("kandungan_merkuri_per_kg"));
                        v2.add(Rs.getString("kandungan_ecoli_per_g"));
                        v2.add(Rs.getString("kandungan_salmolella_ssp_per_25g"));
                }
                DFT.addRow(v2);
            }
            resetText();
            buttonScenario("buka");
            textEnabled(true);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,"Error: " + e);
        }
    }
    
    private void textEnabled(boolean value){
        txtBatch.setEnabled(value);

        txtProtein.setEnabled(value);
        txtKadarAir.setEnabled(value);
        txtLemak.setEnabled(value);

        txtBesi.setEnabled(value);
        txtKalsium.setEnabled(value);    
        txtArsen.setEnabled(value);
        txtKadmium.setEnabled(value);
        txtTimbal.setEnabled(value);
        txtMerkuri.setEnabled(value);

        txtEcoli.setEnabled(value);
        txtSalmonela.setEnabled(value);
    }
    
    private void resetText(){
    txtBatch.setText("");
    
    txtProtein.setText("");
    txtKadarAir.setText("");
    txtLemak.setText("");
    
    txtBesi.setText("");
    txtKalsium.setText("");    
    txtArsen.setText("");
    txtKadmium.setText("");
    txtTimbal.setText("");
    txtMerkuri.setText("");
    
    txtEcoli.setText("");
    txtSalmonela.setText("");
    
    txtSearch.setText("Batch number");
    }
    
    private void buttonScenario(String afterClick){
        switch (afterClick) {
            case "buka":
                bBatalButton.setVisible(false);
                bSimpanButton.setVisible(false);
                bEditButton.setEnabled(false);
                bHapusButton.setEnabled(false);
                bTambahButton.setEnabled(true);
                break;
            case "tabel":
                bBatalButton.setVisible(false);
                bSimpanButton.setVisible(false);
                bEditButton.setEnabled(true);
                bHapusButton.setEnabled(true);
                bTambahButton.setEnabled(false);
                break;
            case "edit":
                bSimpanButton.setVisible(true);
                bBatalButton.setVisible(true);
                bSimpanButton.setEnabled(true);
                bBatalButton.setEnabled(true);
                bEditButton.setEnabled(false);
                bHapusButton.setEnabled(false);
                bTambahButton.setEnabled(false);
                break;
            default:
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrameLabel;
    private javax.swing.JButton bBatalButton;
    private javax.swing.JButton bEditButton;
    private javax.swing.JButton bHapusButton;
    private javax.swing.JButton bSimpanButton;
    private javax.swing.JButton bTambahButton;
    private javax.swing.JButton backMenuButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelArsen;
    private javax.swing.JPanel panelBatch;
    private javax.swing.JPanel panelBesi;
    private javax.swing.JPanel panelEcoli;
    private javax.swing.JPanel panelKadarAir;
    private javax.swing.JPanel panelKadmium;
    private javax.swing.JPanel panelKalsium;
    private javax.swing.JPanel panelLemak;
    private javax.swing.JPanel panelMerkuri;
    private javax.swing.JPanel panelProtein;
    private javax.swing.JPanel panelSalmonela;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelTimbal;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable tableUjiKlinis;
    private javax.swing.JTextField txtArsen;
    private javax.swing.JTextField txtBatch;
    private javax.swing.JTextField txtBesi;
    private javax.swing.JTextField txtEcoli;
    private javax.swing.JTextField txtKadarAir;
    private javax.swing.JTextField txtKadmium;
    private javax.swing.JTextField txtKalsium;
    private javax.swing.JTextField txtLemak;
    private javax.swing.JTextField txtMerkuri;
    private javax.swing.JTextField txtProtein;
    private javax.swing.JTextField txtSalmonela;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTimbal;
    // End of variables declaration//GEN-END:variables
}
