/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basdatgui;

import java.awt.*;
import java.math.*;
import java.sql.*;
import java.text.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
/**
 *
 * @author WINDOWS 11
 */
public class AdminBahanBakuMasuk extends javax.swing.JFrame{

    /**
     * Creates new form AdminBahanBakuMasuk
     */
    public AdminBahanBakuMasuk() {
        initComponents();
        tableUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backMenuButton = new javax.swing.JButton();
        panelTitle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FrameLabel = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBahanMasuk = new javax.swing.JTable();
        bTambahButton = new javax.swing.JButton();
        bHapusButton = new javax.swing.JButton();
        bEditButton = new javax.swing.JButton();
        bBatalButton = new javax.swing.JButton();
        bSimpanButton = new javax.swing.JButton();
        panelID = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelMaterial = new javax.swing.JPanel();
        txtMaterial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panelPrice = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        panelAcqDate = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dateAcq = new com.toedter.calendar.JDateChooser();
        panelSeller = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSeller = new javax.swing.JTextField();
        panelTotalWeight = new javax.swing.JPanel();
        txtTotalWeight = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelTotalPrice = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        backMenuButton.setText("back");
        backMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuButtonActionPerformed(evt);
            }
        });

        panelTitle.setPreferredSize(new java.awt.Dimension(404, 28));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ADMIN");

        FrameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FrameLabel.setText("BAHAN BAKU MASUK");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTitleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FrameLabel))
                    .addGroup(panelTitleLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FrameLabel)
                .addContainerGap())
        );

        searchButton.setText("search");
        searchButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        txtSearch.setText("ID transaksi");
        txtSearch.setToolTipText("");

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addContainerGap())
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tableBahanMasuk.setAutoCreateRowSorter(true);
        tableBahanMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "material", "material price/kg", "acquired date", "seller", "total weight", "total price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBahanMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBahanMasukMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableBahanMasuk);

        bTambahButton.setText("Tambah");
        bTambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahButtonActionPerformed(evt);
            }
        });

        bHapusButton.setText("Hapus");
        bHapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusButtonActionPerformed(evt);
            }
        });

        bEditButton.setText("Edit");
        bEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditButtonActionPerformed(evt);
            }
        });

        bBatalButton.setText("Batal");
        bBatalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalButtonActionPerformed(evt);
            }
        });

        bSimpanButton.setText("Simpan");
        bSimpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanButtonActionPerformed(evt);
            }
        });

        txtID.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel1.setText("ID Transaksi");

        javax.swing.GroupLayout panelIDLayout = new javax.swing.GroupLayout(panelID);
        panelID.setLayout(panelIDLayout);
        panelIDLayout.setHorizontalGroup(
            panelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelIDLayout.setVerticalGroup(
            panelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtMaterial.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel8.setText("Material");

        javax.swing.GroupLayout panelMaterialLayout = new javax.swing.GroupLayout(panelMaterial);
        panelMaterial.setLayout(panelMaterialLayout);
        panelMaterialLayout.setHorizontalGroup(
            panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMaterialLayout.setVerticalGroup(
            panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel5.setText("Material price/kg");

        txtPrice.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelPriceLayout = new javax.swing.GroupLayout(panelPrice);
        panelPrice.setLayout(panelPriceLayout);
        panelPriceLayout.setHorizontalGroup(
            panelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPriceLayout.setVerticalGroup(
            panelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setText("Acquired date");

        dateAcq.setDateFormatString("yyyy-MM-dd");
        dateAcq.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelAcqDateLayout = new javax.swing.GroupLayout(panelAcqDate);
        panelAcqDate.setLayout(panelAcqDateLayout);
        panelAcqDateLayout.setHorizontalGroup(
            panelAcqDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcqDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dateAcq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelAcqDateLayout.setVerticalGroup(
            panelAcqDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcqDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAcqDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dateAcq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jLabel6.setText("Seller");

        txtSeller.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelSellerLayout = new javax.swing.GroupLayout(panelSeller);
        panelSeller.setLayout(panelSellerLayout);
        panelSellerLayout.setHorizontalGroup(
            panelSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSellerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSellerLayout.setVerticalGroup(
            panelSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSellerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtTotalWeight.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel4.setText("Total weight");

        javax.swing.GroupLayout panelTotalWeightLayout = new javax.swing.GroupLayout(panelTotalWeight);
        panelTotalWeight.setLayout(panelTotalWeightLayout);
        panelTotalWeightLayout.setHorizontalGroup(
            panelTotalWeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalWeightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(txtTotalWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTotalWeightLayout.setVerticalGroup(
            panelTotalWeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalWeightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTotalWeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel7.setText("Total price");

        txtTotalPrice.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout panelTotalPriceLayout = new javax.swing.GroupLayout(panelTotalPrice);
        panelTotalPrice.setLayout(panelTotalPriceLayout);
        panelTotalPriceLayout.setHorizontalGroup(
            panelTotalPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTotalPriceLayout.setVerticalGroup(
            panelTotalPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTotalPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                            .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backMenuButton)
                        .addGap(0, 622, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelAcqDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTotalWeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelMaterial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(panelTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panelSeller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(128, 128, 128))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSimpanButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBatalButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bEditButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bHapusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTambahButton)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backMenuButton)
                .addGap(3, 3, 3)
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(panelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAcqDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSeller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTotalWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bTambahButton)
                            .addComponent(bHapusButton)
                            .addComponent(bEditButton)
                            .addComponent(bBatalButton)
                            .addComponent(bSimpanButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuButtonActionPerformed
        new AdminMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMenuButtonActionPerformed

    
    private void tableBahanMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBahanMasukMouseClicked
        tableClicked();
    }//GEN-LAST:event_tableBahanMasukMouseClicked

// Edit button = done
    private void bEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditButtonActionPerformed
        textEnabled(true);
        txtID.setEnabled(false);
        buttonScenario("edit");
    }//GEN-LAST:event_bEditButtonActionPerformed

    private void bBatalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalButtonActionPerformed
        int index = tableBahanMasuk.getSelectedRow();
        tableClicked();
    }//GEN-LAST:event_bBatalButtonActionPerformed

// Delete function = Done    
    private void bHapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableBahanMasuk.getModel();
        int selectedIndex = tableBahanMasuk.getSelectedRow();
        try {   
            int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to delete the record","Warning",JOptionPane.YES_NO_OPTION);
            
            if(dialogResult == JOptionPane.YES_OPTION){
                PreparedStatement delete = sqlQuery("delete from bahan_baku_masuk where id_transaksi = ?");

                delete.setString(1,model.getValueAt(selectedIndex, 0).toString());
                delete.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Delete");
                
                tableUpdate();
           }
        } catch (Exception e) {   
            JOptionPane.showMessageDialog(this,"Exception: " + e);
        }
    }//GEN-LAST:event_bHapusButtonActionPerformed

//create or insert = done    
    private void bTambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahButtonActionPerformed
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            
            PreparedStatement insert = sqlQuery("insert into bahan_baku_masuk(id_transaksi, material, material_per_kg, acquired_date, seller, total_weight, total_price)values(?,?,?,?,?,?,?)");
            insert.setString(1, txtID.getText());
            insert.setString(2, txtMaterial.getText());
            insert.setBigDecimal(3, new BigDecimal(txtPrice.getText()));
            
            insert.setString(4, sdf.format(dateAcq.getDate()));
            
            insert.setString(5, txtSeller.getText());
            insert.setBigDecimal(6, new BigDecimal(txtTotalWeight.getText()));
            insert.setBigDecimal(7, new BigDecimal(txtTotalPrice.getText()));
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Data berhasil ditambahkan!");
            
            tableUpdate();            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error: " + e);
        }
    }//GEN-LAST:event_bTambahButtonActionPerformed

//update function
    private void bSimpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanButtonActionPerformed
        try {   
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            
            DefaultTableModel model = (DefaultTableModel) tableBahanMasuk.getModel();
            int selectedIndex = tableBahanMasuk.getSelectedRow();
            
            PreparedStatement update = sqlQuery("update bahan_baku_masuk "
                    + "set material=?, material_per_kg=?, acquired_date=?, seller=?, total_weight=?, total_price=?"
                    + "where id_transaksi= ?");
            
            update.setString(1, txtMaterial.getText());
            update.setBigDecimal(2, new BigDecimal(txtPrice.getText()));
            
            update.setString(3, sdf.format(dateAcq.getDate()));
            
            update.setString(4, txtSeller.getText());
            update.setBigDecimal(5, new BigDecimal(txtTotalWeight.getText()));
            update.setBigDecimal(6, new BigDecimal(txtTotalPrice.getText()));
            update.setString(7, txtID.getText());
            update.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Record Updated");
            
            tableUpdate();
            tableClicked();
                      
        } catch (HeadlessException | NumberFormatException | SQLException e) {
           JOptionPane.showMessageDialog(this,"Error: " + e);
        }
    }//GEN-LAST:event_bSimpanButtonActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        tableUpdate();
    }//GEN-LAST:event_formMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try{
            PreparedStatement search = sqlQuery("SELECT * FROM bahan_baku_masuk " +
                    "WHERE id_transaksi LIKE ?");

            search.setString(1, "%" + txtSearch.getText() + "%");
                
            String tempSearch = txtSearch.getText();
            loadData(search);
            txtSearch.setText(tempSearch);
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error: " + e);
        }    
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminBahanBakuMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                new AdminBahanBakuMasuk().setVisible(true);
            }
        });
    }
    
    /*
        REQUIRED METHODS
    */
    
    private PreparedStatement sqlQuery (String query){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection url = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=KeinasthaFarma;encrypt=true;trustServerCertificate=true","sa","1211125");
            PreparedStatement getQuery = url.prepareStatement(query);
            return getQuery;
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,"Error: " + e);
        }
        return null;
    }
    
    private void tableUpdate() {
        PreparedStatement display = sqlQuery("SELECT * FROM bahan_baku_masuk");
        loadData(display);
    }
    
    private void tableClicked(){
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            
            int index = tableBahanMasuk.getSelectedRow();
            TableModel model = tableBahanMasuk.getModel();

            txtID.setText(model.getValueAt(index, 0).toString());
            txtMaterial.setText(model.getValueAt(index, 1).toString());
            txtPrice.setText(model.getValueAt(index, 2).toString());
            
            dateAcq.setDate(sdf.parse(model.getValueAt(index, 3).toString()));
            
            txtSeller.setText(model.getValueAt(index, 4).toString());
            txtTotalWeight.setText(model.getValueAt(index, 5).toString());
            txtTotalPrice.setText(model.getValueAt(index, 6).toString());

            textEnabled(false);
            buttonScenario("tabel");
        } catch (ParseException e){
            JOptionPane.showMessageDialog(this,"Error: " + e);
        }
    }
    
    private void loadData(PreparedStatement executeThis){
        try{
            int CC;
            
            ResultSet Rs = executeThis.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) tableBahanMasuk.getModel();
            DFT.setRowCount(0);
            while (Rs.next()) {
                Vector v2 = new Vector();

                for (int ii = 1; ii <= CC; ii++) {
                    v2.add(Rs.getString("id_transaksi"));
                    v2.add(Rs.getString("material"));
                    v2.add(Rs.getString("material_per_kg"));
                    v2.add(Rs.getString("acquired_date"));
                    v2.add(Rs.getString("seller"));
                    v2.add(Rs.getString("total_weight"));
                    v2.add(Rs.getString("total_price"));
                }
                DFT.addRow(v2);
            }
            resetText();
            buttonScenario("buka");
            textEnabled(true);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,"Error: " + e);
        }
    }
       
    private void textEnabled(boolean value){
        txtID.setEnabled(value);
        txtMaterial.setEnabled(value);
        txtPrice.setEnabled(value);
        dateAcq.setEnabled(value);
        txtSeller.setEnabled(value);
        txtTotalWeight.setEnabled(value);
        txtTotalPrice.setEnabled(value);
    }
    
    private void resetText(){
        txtID.setText("");
        txtMaterial.setText("");
        txtPrice.setText("");
        dateAcq.setDate(null);
        txtSeller.setText("");
        txtTotalWeight.setText("");
        txtTotalPrice.setText("");
        
        txtSearch.setText("ID transkasi");
    }
    
    private void buttonScenario(String afterClick){
        switch (afterClick) {
            case "buka":
                bBatalButton.setVisible(false);
                bSimpanButton.setVisible(false);
                bEditButton.setEnabled(false);
                bHapusButton.setEnabled(false);
                bTambahButton.setEnabled(true);
                break;
            case "tabel":
                bBatalButton.setVisible(false);
                bSimpanButton.setVisible(false);
                bEditButton.setEnabled(true);
                bHapusButton.setEnabled(true);
                bTambahButton.setEnabled(false);
                break;
            case "edit":
                bSimpanButton.setVisible(true);
                bBatalButton.setVisible(true);
                bSimpanButton.setEnabled(true);
                bBatalButton.setEnabled(true);
                bEditButton.setEnabled(false);
                bHapusButton.setEnabled(false);
                bTambahButton.setEnabled(false);
                break;
            default:
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrameLabel;
    private javax.swing.JButton bBatalButton;
    private javax.swing.JButton bEditButton;
    private javax.swing.JButton bHapusButton;
    private javax.swing.JButton bSimpanButton;
    private javax.swing.JButton bTambahButton;
    private javax.swing.JButton backMenuButton;
    private com.toedter.calendar.JDateChooser dateAcq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelAcqDate;
    private javax.swing.JPanel panelID;
    private javax.swing.JPanel panelMaterial;
    private javax.swing.JPanel panelPrice;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelSeller;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel panelTotalPrice;
    private javax.swing.JPanel panelTotalWeight;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable tableBahanMasuk;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMaterial;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSeller;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JTextField txtTotalWeight;
    // End of variables declaration//GEN-END:variables
}
