/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basdatgui;

import java.io.*;
import java.sql.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.xml.*;
import net.sf.jasperreports.engine.design.*;

/**
 *
 * @author DELL
 */
public class EmployeeBarangKeluar extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeBarangKeluar
     */
    public EmployeeBarangKeluar() {
        initComponents();
        tableUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tableOut = new javax.swing.JTable();
        backMenuButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        FrameLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        bGetInvoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tableOut.setAutoCreateRowSorter(true);
        tableOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID produk", "nama produk", "batch number", "jumlah kirim", "tanggal produksi", "tanggal kadaluarsa", "bahan baku utama", "harga/kg", "tanggal dokumen kontrak", "pembeli", "sisa kontrak"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOutMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableOut);

        backMenuButton.setText("back");
        backMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuButtonActionPerformed(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(404, 28));

        FrameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FrameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FrameLabel.setText("BARANG KELUAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FrameLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FrameLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchButton.setText("search");
        searchButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        txtSearch.setText("ID produk");
        txtSearch.setToolTipText("");

        bGetInvoice.setText("get invoice");
        bGetInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGetInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bGetInvoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGetInvoice))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backMenuButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backMenuButton)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuButtonActionPerformed
        new EmployeeMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMenuButtonActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        tableUpdate();
    }//GEN-LAST:event_formMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try{
            PreparedStatement search = sqlQuery("SELECT * FROM produk_keluar " +
                    "WHERE id_produk LIKE ?");
            
            search.setString(1, "%" + txtSearch.getText() + "%");
                
            String tempSearch = txtSearch.getText();
            loadData(search);
            txtSearch.setText(tempSearch);
                
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Error: " + e);
        }  
    }//GEN-LAST:event_searchButtonActionPerformed

    private void tableOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOutMouseClicked
        bGetInvoice.setEnabled(true);
    }//GEN-LAST:event_tableOutMouseClicked

    private void bGetInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGetInvoiceActionPerformed
        int index = tableOut.getSelectedRow();
	String ID = tableOut.getValueAt(index, 0).toString();
	try{
            String filePath = "src/basdatgui/invoice.jrxml";
            JasperDesign jasperDesign =  JRXmlLoader.load(new FileInputStream(new File(filePath)));
            JRDesignQuery newQuery = new JRDesignQuery();
	
            String sql = "SELECT "
                        + "pembeli AS nama_customer,"
                        + "Tanggal_dokumen_kontrak AS tanggal_pemesanan,"
                        + "nama_produk,"
                        + "id_produk,"
                        + "tanggal_produksi,"
                        + "tanggal_kadaluwarsa,"
                        + "jumlah_kirim AS jumlah_pesanan,"
                        + "harga_per_kg,"
                        + "(jumlah_kirim * harga_per_kg) AS total "
                        + "FROM produk_keluar "
                        + "WHERE id_produk = " + ID + "";
            newQuery.setText(sql);
            jasperDesign.setQuery(newQuery);
		
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            
            Map<String, Object> paramtr = new HashMap<>();
            paramtr.put("searchFor", ID);
		
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, paramtr, getUrl());
            JasperViewer.viewReport(jasperPrint, false);
            
            String PATH = "uploads/Receipts/";
            File directory = new File(PATH);
            if (!directory.exists()) {
            	directory.mkdirs();
            	// use directory.mkdirs(); here instead.
            	// If you require it to make the entire directory path including parents,
            }
            try (OutputStream os = new FileOutputStream(new File("uploads/Receipts/Seller Reciept-OrderID" + ID + ".pdf"))) {
                JasperExportManager.exportReportToPdfStream(jasperPrint, os);
                JasperViewer.viewReport(jasperPrint, false);
            }
	} catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error! Hubungi Admin!");
            e.printStackTrace();
	}
    }//GEN-LAST:event_bGetInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeBarangKeluar().setVisible(true);
            }
        });
    }
    
    /*
        REQUIRED METHODS
    */
    
    private Connection getUrl (){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection url = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=KeinasthaFarma;encrypt=true;trustServerCertificate=true","sa","1211125");
        return url;
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,"Error: " + e);            
        }
        return null;
    }
    
    private PreparedStatement sqlQuery (String query){
        try{
            PreparedStatement getQuery = getUrl().prepareStatement(query);
            return getQuery;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Error: " + e);
        }
        return null;
    }
    
    private void tableUpdate() {
        PreparedStatement display = sqlQuery("SELECT * FROM produk_keluar");
        loadData(display);
        bGetInvoice.setEnabled(false);
    }
       
    private void loadData(PreparedStatement executeThis){
        try{
            int CC;
            
            ResultSet Rs = executeThis.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) tableOut.getModel();
            DFT.setRowCount(0);
            while (Rs.next()) {
                Vector v2 = new Vector();

                for (int ii = 1; ii <= CC; ii++) {
                    v2.add(Rs.getString("id_produk"));
                    v2.add(Rs.getString("nama_produk"));
                    v2.add(Rs.getString("batch_number"));
                    v2.add(Rs.getString("jumlah_kirim"));
                    v2.add(Rs.getString("tanggal_produksi"));
                    v2.add(Rs.getString("tanggal_kadaluwarsa"));
                    v2.add(Rs.getString("bahan_baku_utama"));
                    v2.add(Rs.getString("harga_per_kg"));
                    v2.add(Rs.getString("tanggal_dokumen_kontrak"));
                    v2.add(Rs.getString("pembeli"));
                    v2.add(Rs.getString("sisa_kontrak"));
                }
                DFT.addRow(v2);
            }
            resetText();
                        
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,"Error: " + e);
        }
    }
    
    private void resetText(){
        txtSearch.setText("ID produk");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrameLabel;
    private javax.swing.JButton bGetInvoice;
    private javax.swing.JButton backMenuButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable tableOut;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
